" General
syntax enable
set background=dark
set nocompatible
set mouse=a

set modeline
set laststatus=2
set noshowmode

" Airline
let g:airline_theme='bubblegum'
let g:airline#extensions#tabline#enabled = 1

" Search
set hlsearch
set incsearch

" Identation
set expandtab
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent

" MatchParen colors
highlight MatchParen cterm=underline ctermfg=red ctermbg=none

" Systemd unit files
au BufNewFile,BufRead */systemd/*.{automount,mount,path,service,socket,swap,target,timer}* setf systemd

" KeyBindings
" Move between buffers
nnoremap <C-Left> :bprevious<CR>
nnoremap <C-Right> :bnext<CR>
" <Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>
