" General
syntax enable
set background=dark
set nocompatible
set mouse=a

set modeline
set laststatus=2
set noshowmode

" Airline
let g:airline_theme='bubblegum'
" let g:airline#extensions#tabline#enabled = 1

" Search
set hlsearch
set incsearch

" Identation
set smarttab
set shiftwidth=4
set tabstop=4
set autoindent
set smartindent
set cindent
set backspace=indent,eol,start

" <Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>
" MatchParen colors
highlight MatchParen cterm=underline ctermfg=red ctermbg=none
